### ISSUE TITLE
Không cài đặt được 

### ISSUE THREAD

**Issue by canhtran10** [doanguyen/lasotuvi-django#1]
Mình dùng MacOS lúc download về có chạy lệnh đầu tiên như hướng dẫn nhưng gặp lỗi này, bạn có thể cho mình tài liệu chi tiêt hơn để mình có thể chạy được project này thì tốt quá, cảm ơn bạn.
Nếu bạn đã có những cập nhật mới có thể share đc thì có thể đến email của mình: quangcanh.dhv@gmail.com . Cảm ơn nhiều.
```
Canhs-MacBook-Pro:lasotuvi-django-master canhtranquang$ pip install django lasotuvi-djang
Collecting django
  Downloading Django-3.0.7-py3-none-any.whl (7.5 MB)
     |████████████████████████████████| 7.5 MB 2.5 MB/s 
ERROR: Could not find a version that satisfies the requirement lasotuvi-djang (from versions: none)
ERROR: No matching distribution found for lasotuvi-djang
(.env) Canhs-MacBook-Pro:lasotuvi-django-master canhtranquang$ 

```

**Comment by doanguyen** [comment]
Bạn gõ thiếu câu lệnh nhé:

`pip install django lasotuvi-django`

**Comment by canhtran10** [comment]
Hi bạn, mình không tìm thấy settings.py
![image](https://user-images.githubusercontent.com/4555599/84572247-fd1cb880-adc2-11ea-80d7-6d79b8dcdeda.png)

**Comment by canhtran10** [comment]
Hi sau khi cố gắng đã đến được bước này:
![image](https://user-images.githubusercontent.com/4555599/84584209-97184b80-ae2b-11ea-95b9-74780709d5b2.png)

Cuối rồi, mong bạn giúp :))

**Comment by canhtran10** [comment]
![image](https://user-images.githubusercontent.com/4555599/84584283-82888300-ae2c-11ea-9cff-3d18ca92c2a2.png)

thank you :))
